In [2]:
import numpy as np

In [3]:
# Creating a NumPy Array
lst = [1, 2, 3, 4]

arr = np.array(lst) # arr = np.array([1, 2, 3, 4]) 동일
print(arr)

[1 2 3 4]


In [4]:
prices = [30, 25, 40, 20, 20, 35, 50 ,35]
new_prices = [price - 5 for price in prices]
print (new_prices)

# With a ndarray
prices_arr = np.array(prices)
prices_arr = prices_arr - 5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [6]:
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])
test_3_fixed = test_3 - 2
print(test_1)
print(test_2)
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3
print(total_grade)

final_grade = total_grade/3
print(final_grade)

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = np.array([test_1[1], test_1[2]])
print(manual_adwoa_test_1)

student_score = np.array([test_1, test_2, test_3])
print(student_score)

print(student_score[2][0])

print(student_score[:, 4])

[92 94 88 91 87]
[ 79 100  86  93  91]
[85 83 70 88 90]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [7]:
a = np.array([10, 2, 2, 4, 5, 3, 9, 8, 9, 7])

mask = a > 5
print(mask)

selected = a[a > 5]
print(selected)

selected = a[(a > 5) | (a < 3)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  9  8  9  7]


In [17]:
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])
print(porridge)

cold = porridge[porridge < 60]
print(cold)
hot = porridge[porridge > 80]
print(hot)
just_right = porridge[(porridge >= 60) & (porridge <= 80)]
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
